### ISSUE TITLE
[Bug]: Code marked as NX when boot Ubuntu

### ISSUE THREAD

**Issue by kuqin12** [Microsoft/mu_silicon_arm_tiano#124]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

There was a report recently on booting Linux ARM64 system, where the system will run into synchronous exception after handing off to Linux bootloader. Where the exception occurs is at the boundary of a memory page. The debugger shows that the code to be executed is marked as not executable from MMU.

The OS is downloaded from below:
https://cdimages.ubuntu.com/jammy/daily-live/pending/

The behavior started to occur after picking up https://github.com/microsoft/mu_silicon_arm_tiano/commit/9bb8982dbc94d7e5d7a553ba80777e2c24f26328 from https://github.com/microsoft/mu_silicon_arm_tiano/commit/17f063737d448935f12696427c1ae6727995b0e8.

### Expected Behavior

System should boot properly.

### Steps To Reproduce

To be tested on QEMU. But otherwise, just build the aforementioned commit and try to boot Ubuntu system.

### Build Environment

```markdown
- OS(s): Ubuntu 2204 nightly build.
- Tool Chain(s): GCC5
- Targets Impacted: DEBUG,RELEASE
```

### Version Information

```text
https://github.com/microsoft/mu_silicon_arm_tiano/commit/9bb8982dbc94d7e5d7a553ba80777e2c24f26328
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by kuqin12** [comment]
The issue was root caused, assigning to @os-d to fill in more information.

**Comment by os-d** [comment]
This was root caused to a Linux shim bug that was already fixed upstream (https://github.com/rhboot/shim/commit/c7b305152802c8db688605654f75e1195def9fd6) but was not carried in the Ubuntu image.

What happened is that the Linux boot shim that was carried attempted to use the Memory Attribute Protocol that was introduced in the commits mentioned above. It would attempt to set the memory attributes for the next image being loaded (fb*.efi in this case) by first setting the entire image region to NX (which was a 4k aligned address and 4k aligned size). Then, it attempted to go section by section of the image and mark any code regions as executable. However, before the shim commit listed above, it would send a non-4k aligned size to the Memory Attribute Protocol, which would return `EFI_INVALID_PARAMETER`, as attributes must be set at a page granularity. The shim then ignored this return value and attempted to start the next image with all of its code sections marked NX, which caused a fault.

The fix is to use a Linux shim with the above commit. There is a workaround to boot `shim*.efi` directly, as this behavior was only seen when the shim is named `boot*.efi`, due to the fallback path it went down. It is not known if there are other pitfalls for this path and the main recommendation is to use a shim with the above commit.

In addition, an issue will be filed with the shim project to check the return value of the memory attribute protocol and at least log it, if not try to take remediate action.

Furthermore, the memory attribute protocol logging will be improved to indicate it is rejecting a request.

**Comment by os-d** [comment]
Filed issue https://github.com/rhboot/shim/issues/575 in the shim to ask to improve logging.
